FROM golang:1.6

ENV GOROOT=/usr/local/go

RUN go get github.com/tools/godep
RUN go get github.com/hudl/fargo

WORKDIR /go/src/github.com/hudl/fargo/
RUN godep restore

#UNcomment if you want to run tests on master branch.
#CMD go test -v ./...
